version: '3.6'

services:
  cloudflare-ddns:
    image: cloudflare-ddns:1.0.0
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        - AUTH_EMAIL=
        - AUTH_KEY=
        - ZONE_IDENTIFIER=
        - RECORD_NAME=